cc_binary(
	name="day2",
	srcs=["day2.cpp"],
)

cc_binary(
	name="day3",
	srcs=["day3.cpp"],
)

cc_binary(
	name="day4",
	srcs=["day4.cpp"],
	copts=["-std=c++20"],
)

cc_binary(
	name="day5",
	srcs=["day5.cpp"],
	copts=["-std=c++20"],
)

